//! Phase 4: Rebuild — Zero-byte-survival PDF reconstruction.
//!
//! This module builds a completely new PDF document from extracted content,
//! guaranteeing that **no bytes** from the original file survive in the output.
//!
//! ## Security Guarantee
//!
//! - New document created from scratch (lopdf::Document::with_version)
//! - Fresh xref table generated by lopdf
//! - Clean catalog with no dangerous entries (no OpenAction, AA, JS, AcroForm)
//! - Reconstructed page tree from validated content streams
//! - MediaBox values inherited/resolved during Extract phase
//! - Optional metadata embedding (if preservation policy allows)
//!
//! ## Performance Design
//!
//! - **Pre-allocated vectors**: Page reference vectors are reserved upfront from
//!   known page counts, avoiding incremental reallocation.
//! - **Output buffer estimation**: Output Vec is pre-sized based on total content
//!   stream bytes plus fixed overhead per page (~2KB per page for dictionary/xref).

#[cfg(feature = "pdf-cdr")]
use std::collections::HashMap;

#[cfg(feature = "pdf-cdr")]
use lopdf::{dictionary, Document, Object, Stream};

#[cfg(feature = "pdf-cdr")]
use super::analyze::ObjectClassification;
use super::extract::ExtractedContent;
use super::types::PdfCdrError;

/// Estimated per-page overhead in the rebuilt PDF (dictionary entries, xref, etc.).
///
/// Used for output buffer pre-allocation heuristic in `rebuild_pdf()`.
const PER_PAGE_OVERHEAD: usize = 2048;

/// Rebuild a completely new PDF document from extracted content.
///
/// This phase guarantees **zero bytes** from the original survive:
/// - New document created from scratch
/// - Fresh xref table generated
/// - Clean catalog (no dangerous entries)
/// - Reconstructed page tree
/// - Validated resources re-embedded
///
/// # Arguments
/// * `content` - Extracted clean content from Phase 3.
/// * `_classification` - Object classification map (reserved for future use).
///
/// # Returns
/// - `Ok(Vec<u8>)` — Rebuilt PDF bytes ready for output
/// - `Err(PdfCdrError)` — Fatal error during PDF generation
#[cfg(feature = "pdf-cdr")]
pub(super) fn rebuild_pdf(
    content: &ExtractedContent,
    _classification: &HashMap<u32, ObjectClassification>,
) -> Result<Vec<u8>, PdfCdrError> {
    let mut doc = Document::with_version("1.5");

    let page_count = content.page_contents.len();
    let mut pages_vec = Vec::with_capacity(page_count);
    let mut page_ref_ids = Vec::with_capacity(page_count);

    // Calculate total content bytes for output buffer estimation
    let total_content_bytes: usize = content.page_contents.iter()
        .map(|pc| pc.len())
        .sum();
    // Estimate output size: content + per-page overhead + trailer/catalog (~4KB)
    let estimated_output_size = total_content_bytes
        .saturating_add(page_count.saturating_mul(PER_PAGE_OVERHEAD))
        .saturating_add(4096);

    for (idx, page_content) in content.page_contents.iter().enumerate() {
        let stream_dict = dictionary! {};
        // Clone is required here because page_contents is borrowed (&ExtractedContent).
        // The Stream takes ownership of the data, so we must clone the borrowed slice.
        // This is the only unavoidable clone in the rebuild phase.
        let stream = Stream::new(stream_dict, page_content.clone()).with_compression(false);

        let content_id = doc.add_object(Stream::from(stream));

        let mediabox = if idx < content.page_mediaboxes.len() {
            content.page_mediaboxes[idx]
        } else {
            [0.0, 0.0, 612.0, 792.0]
        };

        let page_dict = dictionary! {
            b"Type" => "Page",
            b"Parent" => doc.new_object_id(),
            b"MediaBox" => vec![
                mediabox[0].into(),
                mediabox[1].into(),
                mediabox[2].into(),
                mediabox[3].into(),
            ],
            b"Contents" => content_id,
        };

        let page_id = doc.add_object(page_dict);
        page_ref_ids.push(page_id);
        pages_vec.push(Object::Reference(page_id));
    }

    let pages_dict = dictionary! {
        b"Type" => "Pages",
        b"Kids" => pages_vec,
        b"Count" => content.page_contents.len() as i64,
    };

    let pages_id = doc.add_object(pages_dict);

    for page_ref_id in page_ref_ids {
        if let Ok(page_obj) = doc.get_object_mut(page_ref_id) {
            if let Ok(dict) = page_obj.as_dict_mut() {
                dict.set("Parent", Object::Reference(pages_id));
            }
        }
    }

    let catalog_dict = dictionary! {
        b"Type" => "Catalog",
        b"Pages" => Object::Reference(pages_id),
    };

    if let Some(meta) = &content.metadata {
        if !meta.is_empty() {
            let mut info_dict = dictionary! {};
            for (key, value) in meta {
                info_dict.set(key.as_bytes(), Object::String(value.as_bytes().to_vec(), lopdf::StringFormat::Literal));
            }
            let info_id = doc.add_object(Object::Dictionary(info_dict));
            doc.trailer.set("Info", Object::Reference(info_id));
        }
    }

    let catalog_id = doc.add_object(catalog_dict);
    doc.trailer.set("Root", Object::Reference(catalog_id));
    doc.renumber_objects();
    doc.prune_objects();

    // Pre-allocate output buffer with estimated size to reduce reallocation
    let mut output = Vec::with_capacity(estimated_output_size);
    doc.save_to(&mut output)
        .map_err(|e| PdfCdrError::InternalError(format!("Failed to save PDF: {}", e)))?;

    tracing::debug!(
        output_size = output.len(),
        estimated = estimated_output_size,
        pages = page_count,
        "PDF rebuild complete"
    );

    Ok(output)
}
