{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "misogi.sender.fullname" . }}-pdb
  labels:
    {{- include "misogi.sender.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "misogi.sender.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "misogi.receiver.fullname" . }}-pdb
  labels:
    {{- include "misogi.receiver.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "misogi.receiver.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "misogi.smtp.fullname" . }}-pdb
  labels:
    {{- include "misogi.smtp.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "misogi.smtp.selectorLabels" . | nindent 6 }}
{{- end }}
