apiVersion: v1
kind: Service
metadata:
  name: {{ include "misogi.receiver.fullname" . }}
  labels:
    {{- include "misogi.receiver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.receiverConfig.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "misogi.receiver.selectorLabels" . | nindent 4 }}
