/**
 * =============================================================================
 * Misogi WASM — Browser Compatibility Matrix Report Generator
 * =============================================================================
 *
 * Post-test script that parses Playwright JSON results and generates a
 * human-readable Markdown compatibility matrix. This report shows which
 * browsers passed/failed each test, making it easy to identify
 * browser-specific compatibility issues.
 *
 * ## Usage
 *
 * ```bash
 * # Run tests first (generates results.json)
 * npm test
 *
 * # Generate compatibility matrix report
 * node generate-report.js
 *
 * # Output: COMPATIBILITY_MATRIX.md in current directory
 * ```
 *
 * ## Report Contents
 *
 * 1. **Summary Table**: Pass/fail counts per browser project
 * 2. **Detailed Matrix**: Each test × browser cell with status icon
 * 3. **Failure Details**: Error messages and stack traces for failures
 * 4. **Environment Info**: Browser versions, OS, timestamps
 * 5. **Recommendations**: Action items based on test outcomes
 *
 * ## Output Format
 *
 * Generates a GitHub-flavored Markdown file suitable for:
 * - Direct viewing in GitHub/GitLab repositories
 * - Inclusion in CI/CD pipeline artifacts
 * - Attachment to pull request comments
 * - Documentation of supported browser versions
 *
 * @module generate-report
 * @requires ./results.json (generated by Playwright test run)
 * =============================================================================
 */

const fs = require('fs');
const path = require('path');

// =============================================================================
// Configuration
// =============================================================================

/** Input file path (Playwright JSON report output). */
const RESULTS_FILE = path.join(__dirname, 'results.json');

/** Output file path (generated compatibility matrix). */
const OUTPUT_FILE = path.join(__dirname, 'COMPATIBILITY_MATRIX.md');

/** Status icons for visual matrix display (GitHub-flavored Markdown compatible). */
const ICONS = {
  passed: '✅',
  failed: '❌',
  skipped: '⏭️',
  timedOut: '⏱️',
  unknown: '❓',
};

/** ANSI color codes for terminal output (optional enhancement). */
const COLORS = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
};

// =============================================================================
// Main Function
// =============================================================================

/**
 * Main entry point for report generation.
 *
 * Reads Playwright JSON results, processes them into a compatibility matrix,
 * and writes the formatted Markdown report to disk.
 */
function main() {
  console.log('\n📊 Misogi WASM Browser Compatibility Report Generator');
  console.log('=' .repeat(50));

  /** Check if results file exists. */
  if (!fs.existsSync(RESULTS_FILE)) {
    console.error(
      `${COLORS.red}Error:${COLORS_RESET} Results file not found: ${RESULTS_FILE}\n` +
      `Run tests first: ${COLORS.cyan}npm test${COLORS_RESET}`
    );
    process.exit(1);
  }

  /** Read and parse the Playwright JSON report. */
  console.log(`\nReading results from: ${RESULTS_FILE}`);
  const rawData = fs.readFileSync(RESULTS_FILE, 'utf-8');
  const results = JSON.parse(rawData);

  /** Process results into structured data for report generation. */
  const reportData = processResults(results);

  /** Generate the Markdown compatibility matrix. */
  const markdown = generateMarkdownReport(reportData);

  /** Write the report to disk. */
  fs.writeFileSync(OUTPUT_FILE, markdown, 'utf-8');

  /** Print summary to console. */
  printConsoleSummary(reportData);

  console.log(`\n${COLORS.green}✓ Report generated: ${OUTPUT_FILE}${COLORS.reset}\n`);
}

// =============================================================================
// Data Processing
// =============================================================================

/**
 * Process raw Playwright results into structured compatibility data.
 *
 * Transforms the flat suite/test structure from Playwright's JSON format
 * into a matrix format (tests × browsers) suitable for tabular display.
 *
 * @param {Object} results - Raw Playwright JSON report object.
 * @returns {Object} Structured data with suites, browsers, and matrix.
 */
function processResults(results) {
  const suites = [];
  const browsers = new Set();
  const matrix = {}; // { suiteName: { testName: { browserName: status } } }

  /**
   * Recursively extract test results from suite structure.
   * Playwright nests suites within suites, so we traverse the tree.
   */
  function extractTests(suite, suitePath = []) {
    const currentPath = [...suitePath, suite.title];

    /** Process individual test cases. */
    if (suite.tests && Array.isArray(suite.tests)) {
      for (const test of suite.tests) {
        const testName = test.title;
        const browserName = test.projectName || 'unknown';

        /** Track unique browser names for column headers. */
        browsers.add(browserName);

        /** Initialize nested structure if needed. */
        const suiteKey = currentPath.join(' > ');
        if (!matrix[suiteKey]) {
          matrix[suiteKey] = {};
        }
        if (!matrix[suiteKey][testName]) {
          matrix[suiteKey][testName] = {};
        }

        /** Determine test status from result code. */
        let status;
        switch (test.status) {
          case 'expected':
          case 'passed':
            status = 'passed';
            break;
          case 'unexpected':
          case 'failed':
            status = 'failed';
            break;
          case 'skipped':
          case 'pending':
            status = 'skipped';
            break;
          case 'timedOut':
            status = 'timedOut';
            break;
          default:
            status = 'unknown';
        }

        /** Store status and optional error details. */
        matrix[suiteKey][testName][browserName] = {
          status,
          duration: test.duration || 0,
          error: test.errors?.[0]?.message || null,
        };
      }
    }

    /** Recurse into child suites. */
    if (suite.suites && Array.isArray(suite.suites)) {
      for (const childSuite of suite.suites) {
        extractTests(childSuite, currentPath);
      }
    }

    /** Register this suite if it has tests. */
    if (suite.tests?.length > 0) {
      suites.push({
        name: currentPath.join(' > '),
        title: suite.title,
      });
    }
  }

  /** Start extraction from root suite. */
  if (results.suites) {
    for (const suite of results.suites) {
      extractTests(suite);
    }
  }

  return {
    suites,
    browsers: Array.from(browsers).sort(),
    matrix,
    metadata: {
      generatedAt: new Date().toISOString(),
      totalSuites: suites.length,
      totalBrowsers: browsers.size,
    },
  };
}

// =============================================================================
// Markdown Generation
// =============================================================================

/**
 * Generate a comprehensive Markdown compatibility matrix report.
 *
 * Creates a well-formatted document with:
 * - Title and metadata header
 * - Summary statistics table
 * - Detailed test-by-test matrix
 * - Failure details section
 * - Environment information
 *
 * @param {Object} reportData - Processed report data from processResults().
 * @returns {string} Complete Markdown document content.
 */
function generateMarkdownReport(reportData) {
  const { suites, browsers, matrix, metadata } = reportData;

  /** Calculate summary statistics per browser. */
  const summary = calculateSummary(browsers, matrix);

  /** Start building the Markdown document. */
  const lines = [];

  // -------------------------------------------------------------------------
  // Header Section
  // -------------------------------------------------------------------------

  lines.push('# Misogi WASM — Browser Compatibility Matrix');
  lines.push('');
  lines.push(
    '**Generated:** ' + formatDate(metadata.generatedAt) + '  \n' +
    '**Total Test Suites:** ' + metadata.totalSuites + '  \n' +
    '**Browser Configurations:** ' + metadata.totalBrowsers
  );
  lines.push('');

  // -------------------------------------------------------------------------
  // Summary Table
  // -------------------------------------------------------------------------

  lines.push('## Executive Summary');
  lines.push('');
  lines.push('| Browser | Passed | Failed | Skipped | Pass Rate |');
  lines.push('|---------|--------|--------|---------|-----------|');

  for (const browser of browsers) {
    const stats = summary[browser];
    const passRate = stats.total > 0
      ? ((stats.passed / stats.total) * 100).toFixed(1) + '%'
      : 'N/A';

    lines.push(
      `| ${browser} | ${stats.passed} | ${stats.failed} | ` +
      `${stats.skipped} | ${passRate} |`
    );
  }

  lines.push('');

  // -------------------------------------------------------------------------
  // Overall Status Badge
  // -------------------------------------------------------------------------

  const allPassed = browsers.every(b => summary[b].failed === 0);
  const overallStatus = allPassed
    ? '✅ **All tests passing across all browsers**'
    : '⚠️ **Failures detected — see details below**';

  lines.push(`> ${overallStatus}`);
  lines.push('');

  // -------------------------------------------------------------------------
  // Detailed Compatibility Matrix
  // -------------------------------------------------------------------------

  lines.push('## Detailed Test Matrix');
  lines.push('');
  lines.push(
    'Legend: ' +
    `${ICONS.passed} Passed | ` +
    `${ICONS.failed} Failed | ` +
    `${ICONS.skipped} Skipped | ` +
    `${ICONS.timedOut} Timed Out`
  );
  lines.push('');

  /** Generate matrix table for each test suite. */
  for (const suite of suites) {
    lines.push(`### ${suite.name}`);
    lines.push('');

    /** Table header: Test name + browser columns. */
    let headerLine = '| Test Case |';
    let separatorLine = '|-----------|';

    for (const browser of browsers) {
      headerLine += ` ${browser} |`;
      separatorLine += '----------|';
    }

    lines.push(headerLine);
    lines.push(separatorLine);

    /** Get all tests in this suite (preserve insertion order). */
    const testsInSuite = matrix[suite.name] || {};

    for (const [testName, browserResults] of Object.entries(testsInSuite)) {
      let row = `| ${testName} |`;

      for (const browser of browsers) {
        const result = browserResults[browser];
        const status = result ? result.status : 'unknown';
        const icon = ICONS[status] || ICONS.unknown;

        row += ` ${icon} |`;
      }

      lines.push(row);
    }

    lines.push('');
  }

  // -------------------------------------------------------------------------
  // Failure Details
  // -------------------------------------------------------------------------

  const failures = collectFailures(matrix);

  if (failures.length > 0) {
    lines.push('## Failure Details');
    lines.push('');
    lines.push(
      `> ⚠️ **${failures.length} test(s)** failed across browser configurations. ` +
      `Review the error messages below for debugging information.`
    );
    lines.push('');

    for (let i = 0; i < failures.length; i++) {
      const failure = failures[i];

      lines.push(`### Failure #${i + 1}: ${failure.testName}`);
      lines.push('');
      lines.push('- **Suite:** ' + failure.suiteName);
      lines.push('- **Browser:** ' + failure.browser);
      lines.push('- **Duration:** ' + formatDuration(failure.duration));
      lines.push('');
      lines.push('**Error Message:**');
      lines.push('');
      lines.push('```');
      lines.push(failure.error || 'No error message available');
      lines.push('```');
      lines.push('');
    }
  } else {
    lines.push('## Failure Details');
    lines.push('');
    lines.push('_No failures detected. All tests passed successfully._ ✨');
    lines.push('');
  }

  // -------------------------------------------------------------------------
  // Recommendations
  // -------------------------------------------------------------------------

  lines.push('## Recommendations');
  lines.push('');

  const recommendations = generateRecommendations(summary, failures);

  for (const rec of recommendations) {
    lines.push(`- ${rec}`);
  }

  lines.push('');

  // -------------------------------------------------------------------------
  // Footer
  // -------------------------------------------------------------------------

  lines.push('---');
  lines.push('');
  lines.push(
    '*Generated by [Misogi WASM](https://github.com/misogi-project/misogi) ' +
    'browser compatibility test framework.*'
  );
  lines.push('');

  return lines.join('\n');
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Calculate pass/fail/skip counts per browser configuration.
 *
 * Iterates through all test results and aggregates statistics for each
 * browser project. Used for the executive summary table.
 *
 * @param {string[]} browsers - List of browser project names.
 * @param {Object} matrix - Test results matrix.
 * @returns {Object} Map of browser name → statistics object.
 */
function calculateSummary(browsers, matrix) {
  const summary = {};

  /** Initialize counters for each browser. */
  for (const browser of browsers) {
    summary[browser] = { passed: 0, failed: 0, skipped: 0, total: 0 };
  }

  /** Count results across all suites and tests. */
  for (const suiteData of Object.values(matrix)) {
    for (const testData of Object.values(suiteData)) {
      for (const browser of browsers) {
        const result = testData[browser];
        if (result) {
          summary[browser].total++;

          switch (result.status) {
            case 'passed':
              summary[browser].passed++;
              break;
            case 'failed':
              summary[browser].failed++;
              break;
            case 'skipped':
            case 'timedOut':
              summary[browser].skipped++;
              break;
          }
        }
      }
    }
  }

  return summary;
}

/**
 * Collect all failed test results with error details.
 *
 * Extracts failure information from the matrix for detailed reporting.
 * Each failure includes suite name, test name, browser, duration, and error.
 *
 * @param {Object} matrix - Test results matrix.
 * @returns {Array} List of failure objects with diagnostic information.
 */
function collectFailures(matrix) {
  const failures = [];

  for (const [suiteName, suiteData] of Object.entries(matrix)) {
    for (const [testName, testData] of Object.entries(suiteData)) {
      for (const [browser, result] of Object.entries(testData)) {
        if (result && result.status === 'failed') {
          failures.push({
            suiteName,
            testName,
            browser,
            duration: result.duration,
            error: result.error,
          });
        }
      }
    }
  }

  return failures;
}

/**
 * Generate actionable recommendations based on test results.
 *
 * Analyzes the summary statistics and failure patterns to provide
 * specific guidance for developers on how to address issues.
 *
 * @param {Object} summary - Per-browser pass/fail statistics.
 * @param {Array} failures - List of failure details.
 * @returns {Array} List of recommendation strings.
 */
function generateRecommendations(summary, failures) {
  const recommendations = [];

  /** Check if all tests pass. */
  const allPass = Object.values(summary).every(s => s.failed === 0);

  if (allPass) {
    recommendations.push(
      '✅ All tests are passing. No immediate action required.'
    );
    return recommendations;
  }

  /** Identify browsers with failures. */
  const failingBrowsers = Object.entries(summary)
    .filter(([, s]) => s.failed > 0)
    .map(([browser, s]) => ({
      browser,
      failCount: s.failed,
      passRate: ((s.passed / s.total) * 100).toFixed(1),
    }));

  if (failingBrowsers.length > 0) {
    recommendations.push(
      '⚠️ **Browser(s) with failures:**'
    );

    for (const { browser, failCount, passRate } of failingBrowsers) {
      recommendations.push(
        `  - **${browser}:** ${failCount} failed (${passRate}% pass rate)`
      );
    }

    recommendations.push('');
  }

  /** Analyze failure patterns. */
  const failurePatterns = analyzeFailurePatterns(failures);

  if (failurePatterns.isolatedToBrowser) {
    recommendations.push(
      '🔍 Failures appear isolated to specific browser(s). Consider:'
    );
    recommendations.push(
      '  - Checking browser-specific API differences (e.g., WebKit vs Blink)'
    );
    recommendations.push(
      '  - Reviewing polyfills or feature detection logic'
    );
    recommendations.push(
      '  - Testing on physical devices (not just emulated browsers)'
    );
    recommendations.push('');
  }

  if (failurePatterns.isolatedToTest) {
    recommendations.push(
      '🔍 Specific test(s) failing across multiple browsers:'
    );
    recommendations.push(
      '  - Review recent changes to affected test scenarios'
    );
    recommendations.push(
      '  - Check for timing/synchronization issues (increase timeouts?)'
    );
    recommendations.push(
      '  - Verify test fixtures and test data validity'
    );
    recommendations.push('');
  }

  /** General recommendations. */
  recommendations.push(
    '📋 General next steps:'
  );
  recommendations.push(
    '  1. Review failure details above for specific error messages'
  );
  recommendations.push(
    '  2. Run tests locally with `npm run test:headed` for visual debugging'
  );
  recommendations.push(
    '  3. Check HTML report (`npm run report`) for screenshots and traces'
  );
  recommendations.push(
    '  4. Fix identified issues and re-run tests to verify resolution'
  );

  return recommendations;
}

/**
 * Analyze failure patterns to categorize issue types.
 *
 * Determines whether failures are:
 * - Isolated to specific browsers (browser-compat bug)
 * - Isolated to specific tests (test code bug)
 * - Widespread (systemic infrastructure issue)
 *
 * @param {Array} failures - List of failure objects.
 * @returns {Object} Pattern analysis flags.
 */
function analyzeFailurePatterns(failures) {
  if (failures.length === 0) {
    return { isolatedToBrowser: false, isolatedToTest: false };
  }

  /** Get unique browsers and tests that have failures. */
  const failingBrowsers = new Set(failures.map(f => f.browser));
  const failingTests = new Set(failures.map(f => f.testName));

  return {
    /** True if failures only affect subset of browsers. */
    isolatedToBrowser: failingBrowsers.size < 3,

    /** True if failures only affect subset of tests. */
    isolatedToTest: failingTests.size < failures.length,
  };
}

/**
 * Format an ISO timestamp to human-readable date string.
 *
 * @param {string} isoString - ISO 8601 formatted date/time string.
 * @returns {string} Formatted date string (e.g., "2026-01-15 14:30 UTC").
 */
function formatDate(isoString) {
  try {
    const date = new Date(isoString);
    return date.toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
  } catch {
    return isoString;
  }
}

/**
 * Format duration in milliseconds to human-readable string.
 *
 * @param {number} ms - Duration in milliseconds.
 * @returns {string} Formatted duration (e.g., "1.234s" or "567ms").
 */
function formatDuration(ms) {
  if (ms >= 1000) {
    return (ms / 1000).toFixed(3) + 's';
  }
  return Math.round(ms) + 'ms';
}

/**
 * Print a colorized summary to the terminal console.
 *
 * Provides quick feedback without needing to open the Markdown file.
 * Uses ANSI color codes for visual clarity (works in most terminals).
 *
 * @param {Object} reportData - Processed report data.
 */
function printConsoleSummary(reportData) {
  const { browsers, metadata, matrix } = reportData;
  const summary = calculateSummary(browsers, matrix);

  console.log('\n📈 Quick Summary:');
  console.log('-'.repeat(40));

  for (const browser of browsers) {
    const stats = summary[browser];
    const passRate = stats.total > 0
      ? ((stats.passed / stats.total) * 100).toFixed(1)
      : '0.0';

    const statusColor = stats.failed > 0 ? COLORS.red : COLORS.green;
    const statusIcon = stats.failed > 0 ? '❌' : '✅';

    console.log(
      `  ${statusIcon} ${browser.padEnd(20)} ` +
      `${COLORS.cyan}${stats.passed}/${stats.total} passed${COLORS.reset} ` +
      `(${statusColor}${passRate}%${COLORS.reset})`
    );
  }

  console.log('-'.repeat(40));
}

// =============================================================================
// Execute
// =============================================================================

/** Run the main function when script is executed directly. */
if (require.main === module) {
  main();
}

/** Export functions for testing purposes. */
module.exports = {
  main,
  processResults,
  generateMarkdownReport,
  calculateSummary,
  collectFailures,
};
