//! Approval execution engine for ABAC obligation fulfillment.
//!
//! Provides [`ApprovalExecutor`], which manages the lifecycle of approval
//! requests generated by policy obligations (`Obligation::RequireApproval`).
//!
//! # Approval Lifecycle
//!
//! ```text
//! Policy Rule matches with RequireApproval obligation
//!     |
//!     v
//! execute_template()  -->  select_approvers()  -->  create_approval_request()
//!     |                      |                         |
//!     v                      v                         v
//! Pending Request      Approvers selected         Trigger callback invoked
//!     |
//!     +-- record_approval()  -->  Auto-complete when threshold met
//!     |                           -> Approved / Rejected
//!     |
//!     +-- handle_timeout()   -->  Escalated or TimedOut
//!     |
//!     +-- cancel_request()    -->  Cancelled
//! ```
//!
//! # Concurrency Model
//!
//! - **Templates**: Immutable after registration; replaced atomically via
//!   [`register_template`](ApprovalExecutor::register_template).
//! - **Active requests**: Protected by `RwLock`; concurrent reads allowed.
//! - **Approver tracking**: Each request tracks per-approver decisions internally.

#[cfg(test)]
mod tests;
mod types;

// Re-export public types from submodule for external consumers.
pub use types::{
    ApprovalRequest, AbacApprovalStatus, ExecutorError,
};

use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::RwLock;

use chrono::Utc;
use uuid::Uuid;

use super::attribute::AbacValue;
use super::policy::{ApprovalTemplate, ApproverPool};
use self::types::ApproverDecisionTracker;

// ===========================================================================
// ApprovalExecutor
// ===========================================================================

/// Manages approval request lifecycle for ABAC obligation fulfillment.
///
/// The executor is the runtime component that bridges policy-defined approval
/// templates with concrete approval workflows. When the ABAC engine produces
/// a decision with `Obligation::RequireApproval`, the caller invokes this
/// executor to create and manage the resulting approval request.
///
/// # Architecture
///
/// ```text
/// AbacEngine (evaluates rules)
///     |
///     | Obligation::RequireApproval(template_id)
///     v
/// ApprovalExecutor
///     |-- templates: HashMap<String, ApprovalTemplate>
///     |-- active_requests: RwLock<HashMap<String, ApprovalRequest>>
///     |-- approver_tracking: RwLock<HashMap<String, ApproverDecisionTracker>>
///     |-- trigger_callback: Option<Fn(ApprovalRequest) -> Future>
/// ```
///
/// # Thread Safety
///
/// All mutable internal state is protected by `RwLock`. Concurrent calls to
/// read-only methods ([`get_request_status`], [`list_pending_for_approver`])
/// do not block each other. Write operations acquire exclusive access briefly.
pub struct ApprovalExecutor {
    /// Registry of available approval templates, keyed by `template_id`.
    templates: RwLock<HashMap<String, ApprovalTemplate>>,

    /// Currently active (non-terminal) approval requests, keyed by `request_id`.
    active_requests: RwLock<HashMap<String, ApprovalRequest>>,

    /// Per-request tracker for individual approver decisions.
    /// Keyed by `request_id`; exists only for pending requests.
    approver_tracking: RwLock<HashMap<String, ApproverDecisionTracker>>,

    /// Optional async callback invoked when a new approval request is created.
    trigger_callback:
        Option<Box<dyn Fn(ApprovalRequest) -> Pin<Box<dyn Future<Output = ()> + Send>> + Send + Sync>>,
}

impl ApprovalExecutor {
    /// Constructs a new executor with the given templates but no trigger callback.
    ///
    /// Use [`with_trigger`](Self::with_trigger) if external notification on
    /// request creation is required.
    pub fn new(templates: Vec<ApprovalTemplate>) -> Self {
        let template_map: HashMap<String, ApprovalTemplate> = templates
            .into_iter()
            .map(|t| (t.template_id.clone(), t))
            .collect();

        Self {
            templates: RwLock::new(template_map),
            active_requests: RwLock::new(HashMap::new()),
            approver_tracking: RwLock::new(HashMap::new()),
            trigger_callback: None,
        }
    }

    /// Constructs a new executor with an async trigger callback.
    ///
    /// The callback is invoked (via tokio::spawn) every time a new approval
    /// request is created. It receives a clone of the request and should
    /// handle notification delivery asynchronously.
    pub fn with_trigger<F>(templates: Vec<ApprovalTemplate>, callback: F) -> Self
    where
        F: Fn(ApprovalRequest) -> Pin<Box<dyn Future<Output = ()> + Send>>
            + Send
            + Sync
            + 'static,
    {
        let mut exec = Self::new(templates);
        exec.trigger_callback = Some(Box::new(callback));
        exec
    }

    // -------------------------------------------------------------------
    // Core Execution
    // -------------------------------------------------------------------

    /// Executes an approval template: selects approvers and creates a pending request.
    ///
    /// This is the primary entry point for fulfilling an
    /// `Obligation::RequireApproval` obligation produced by the ABAC engine.
    pub fn execute_template(
        &self,
        template_id: &str,
        triggered_by_rule: &str,
        subject_user_id: &str,
        resource_description: &str,
        attribute_map: &HashMap<String, AbacValue>,
    ) -> Result<ApprovalRequest, ExecutorError> {
        let templates = self.templates.read().map_err(|_| {
            ExecutorError::TemplateNotFound(template_id.to_string())
        })?;
        let template = templates.get(template_id).ok_or_else(|| {
            ExecutorError::TemplateNotFound(template_id.to_string())
        })?;

        let selected_approvers = self.select_approvers(template, attribute_map);
        if selected_approvers.is_empty() {
            return Err(ExecutorError::NoApproversAvailable);
        }

        let request = self.create_approval_request(
            template,
            triggered_by_rule,
            subject_user_id,
            resource_description,
            selected_approvers,
        );

        if let Some(ref cb) = self.trigger_callback {
            let req_clone = request.clone();
            let future = (cb)(req_clone);
            #[cfg(feature = "runtime")]
            tokio::spawn(async move { future.await });
            #[cfg(not(feature = "runtime"))]
            drop(future);
        }

        Ok(request)
    }

    // -------------------------------------------------------------------
    // Approver Selection
    // -------------------------------------------------------------------

    /// Selects approvers from the template's [`ApproverPool`] based on attributes.
    fn select_approvers(
        &self,
        template: &ApprovalTemplate,
        attribute_map: &HashMap<String, AbacValue>,
    ) -> Vec<String> {
        match &template.approver_pool {
            ApproverPool::Role { roles } => self.resolve_role_approvers(roles, attribute_map),
            ApproverPool::DepartmentHead => self.resolve_department_head(attribute_map),
            ApproverPool::CustomList { user_ids } => user_ids.clone(),
        }
    }

    /// Resolves role-based approvers from the attribute map.
    fn resolve_role_approvers(
        &self,
        roles: &[String],
        attribute_map: &HashMap<String, AbacValue>,
    ) -> Vec<String> {
        let mut result = Vec::new();
        for role in roles {
            let key = format!("role_members_{}", role.to_lowercase());
            if let Some(AbacValue::List(members)) = attribute_map.get(&key) {
                for member in members {
                    if let Some(uid) = member.as_str() {
                        result.push(uid.to_string());
                    }
                }
            }
        }
        result
    }

    /// Resolves the department head approver from the attribute map.
    fn resolve_department_head(
        &self,
        attribute_map: &HashMap<String, AbacValue>,
    ) -> Vec<String> {
        match attribute_map.get("department_head") {
            Some(AbacValue::String(head_id)) if !head_id.is_empty() => vec![head_id.clone()],
            _ => vec![],
        }
    }

    // -------------------------------------------------------------------
    // Request Creation
    // -------------------------------------------------------------------

    /// Creates and registers a new approval request in `Pending` state.
    fn create_approval_request(
        &self,
        template: &ApprovalTemplate,
        triggered_by_rule: &str,
        subject_user_id: &str,
        resource_description: &str,
        selected_approvers: Vec<String>,
    ) -> ApprovalRequest {
        use types::AbacApprovalStatus;

        let request = ApprovalRequest {
            request_id: Uuid::new_v4().to_string(),
            template_id: template.template_id.clone(),
            triggered_by_rule: triggered_by_rule.to_string(),
            subject_user_id: subject_user_id.to_string(),
            resource_description: resource_description.to_string(),
            required_approvers: template.required_approvers,
            selected_approvers: selected_approvers.clone(),
            timeout_hours: template.timeout_hours,
            created_at: Utc::now(),
            status: AbacApprovalStatus::Pending,
            escalation_on_timeout: template.escalation_on_timeout,
        };

        let tracker = ApproverDecisionTracker::new();
        if let Ok(mut tracking) = self.approver_tracking.write() {
            tracking.insert(request.request_id.clone(), tracker);
        }
        if let Ok(mut requests) = self.active_requests.write() {
            requests.insert(request.request_id.clone(), request.clone());
        }
        request
    }

    // -------------------------------------------------------------------
    // Timeout Handling
    // -------------------------------------------------------------------

    /// Handles timeout for a pending approval request.
    pub async fn handle_timeout(&self, request_id: &str) -> Result<AbacApprovalStatus, ExecutorError> {
        use types::AbacApprovalStatus;

        let mut requests = self.active_requests.write().map_err(|_| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;

        let request = requests.get_mut(request_id).ok_or_else(|| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;

        if request.status != AbacApprovalStatus::Pending {
            return Err(ExecutorError::InvalidStateTransition {
                request_id: request_id.to_string(),
                current_state: request.status.clone(),
            });
        }

        let new_status = if request.escalation_on_timeout {
            AbacApprovalStatus::Escalated
        } else {
            AbacApprovalStatus::TimedOut
        };
        request.status = new_status.clone();

        if let Ok(mut tracking) = self.approver_tracking.write() {
            tracking.remove(request_id);
        }
        Ok(new_status)
    }

    // -------------------------------------------------------------------
    // Approval Recording
    // -------------------------------------------------------------------

    /// Records an approval decision from an approver.
    pub fn record_approval(
        &self,
        request_id: &str,
        approver_id: &str,
        approved: bool,
    ) -> Result<AbacApprovalStatus, ExecutorError> {
        use types::AbacApprovalStatus;

        let mut requests = self.active_requests.write().map_err(|_| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;
        let request = requests.get_mut(request_id).ok_or_else(|| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;

        if request.status != AbacApprovalStatus::Pending {
            return Err(ExecutorError::InvalidStateTransition {
                request_id: request_id.to_string(),
                current_state: request.status.clone(),
            });
        }

        let mut tracking = self.approver_tracking.write().map_err(|_| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;
        let tracker = tracking.get_mut(request_id).ok_or_else(|| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;

        if !tracker.responded.insert(approver_id.to_string()) {
            return Err(ExecutorError::DuplicateApproval(approver_id.to_string()));
        }

        if approved {
            tracker.approval_count += 1;
        } else {
            tracker.has_rejection = true;
        }

        let new_status = if tracker.has_rejection {
            AbacApprovalStatus::Rejected
        } else if tracker.approval_count >= request.required_approvers {
            AbacApprovalStatus::Approved
        } else {
            return Ok(AbacApprovalStatus::Pending);
        };

        request.status = new_status.clone();
        tracking.remove(request_id);
        Ok(new_status)
    }

    // -------------------------------------------------------------------
    // Query Operations
    // -------------------------------------------------------------------

    /// Retrieves the current state of an approval request.
    pub fn get_request_status(&self, request_id: &str) -> Option<ApprovalRequest> {
        self.active_requests
            .read()
            .ok()
            .and_then(|r| r.get(request_id).cloned())
    }

    /// Lists all pending approval requests where the given user is an eligible approver.
    pub fn list_pending_for_approver(&self, approver_id: &str) -> Vec<ApprovalRequest> {
        self.active_requests
            .read()
            .ok()
            .map(|r| {
                r.values()
                    .filter(|req| {
                        req.is_pending()
                            && req.selected_approvers.iter().any(|a| a == approver_id)
                    })
                    .cloned()
                    .collect()
            })
            .unwrap_or_default()
    }

    // -------------------------------------------------------------------
    // Template Management
    // -------------------------------------------------------------------

    /// Registers or updates an approval template at runtime.
    pub fn register_template(&self, template: ApprovalTemplate) {
        if let Ok(mut t) = self.templates.write() {
            t.insert(template.template_id.clone(), template);
        }
    }

    // -------------------------------------------------------------------
    // Cancellation
    // -------------------------------------------------------------------

    /// Cancels a pending approval request.
    pub fn cancel_request(&self, request_id: &str) -> Result<(), ExecutorError> {
        use types::AbacApprovalStatus;

        let mut requests = self.active_requests.write().map_err(|_| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;
        let request = requests.get_mut(request_id).ok_or_else(|| {
            ExecutorError::RequestNotFound(request_id.to_string())
        })?;

        if request.status != AbacApprovalStatus::Pending {
            return Err(ExecutorError::InvalidStateTransition {
                request_id: request_id.to_string(),
                current_state: request.status.clone(),
            });
        }

        request.status = AbacApprovalStatus::Cancelled;
        if let Ok(mut tracking) = self.approver_tracking.write() {
            tracking.remove(request_id);
        }
        Ok(())
    }
}
