//! Global runtime plugin registry for Misogi's declarative macro SDK.
//!
//! This module provides a singleton [`PluginRegistry`] that serves as the central
//! discovery point for all plugins registered via the
//! [`#[misogi_plugin]`](misogi_macros::misogi_plugin) attribute macro.
//!
//! # Architecture
//!
//! ```text
//! ┌──────────────────────────────────────────────────────┐
//! │                   GLOBAL_REGISTRY                     │
//! │  Lazy<PluginRegistry> (once_cell, thread-safe init)  │
//! │  ┌────────────────────────────────────────────────┐  │
//! │  │ inner: RwLock<HashMap<String, PluginEntry>>    │  │
//! │  │                                                │  │
//! │  │ "korea_fss_compliance" → PluginEntry { ... }   │  │
//! │  │ "nist_zta_enforcer"     → PluginEntry { ... }   │  │
//! │  │ "acsc_au_scanner"       → PluginEntry { ... }   │  │
//! │  └────────────────────────────────────────────────┘  │
//! └──────────────────────────────────────────────────────┘
//!          ↑ register()           ↓ list_plugins()
//!     #[ctor] auto-reg         get_plugin()
//! ```
//!
//! # Thread Safety
//!
//! The registry uses `parking_lot::RwLock` for:
//! - **Multiple concurrent readers**: `list_plugins()`, `get_plugin()`, `plugin_count()`
//! - **Exclusive writer**: `register()` (called once per plugin at startup)
//!
//! The [`GLOBAL_REGISTRY`] is initialized lazily via `once_cell::sync::Lazy`,
//! guaranteeing it exists before any `#[ctor]` registration function runs.

use std::collections::HashMap;
use std::sync::Arc;

use parking_lot::RwLock;
use once_cell::sync::Lazy;

use crate::traits::PluginMetadata;

/// Metadata stored for each registered plugin in the registry.
#[derive(Debug, Clone)]
pub struct PluginEntry {
    /// Unique plugin identifier (matches [`PluginMetadata::name()`]).
    pub name: String,

    /// SemVer version string.
    pub version: String,

    /// Optional human-readable description.
    pub description: Option<String>,

    /// List of implemented interface names (from [`PluginMetadata::implemented_interfaces()`]).
    pub interfaces: Vec<String>,
}

/// Global, thread-safe plugin registry instance.
///
/// Initialized lazily on first access. All plugins registered via
/// `#[misogi_plugin]` are automatically inserted into this registry
/// at program startup (before `main()` runs).
pub static GLOBAL_REGISTRY: Lazy<PluginRegistry> = Lazy::new(|| {
    tracing::info!("Initializing Misogi Global Plugin Registry");
    PluginRegistry {
        inner: RwLock::new(HashMap::new()),
    }
});

/// Runtime registry for discovering and querying registered Misogi plugins.
///
/// Plugins are registered at startup via `#[ctor]` functions generated by
/// `#[misogi_plugin]`. After registration, they can be queried by name,
/// listed in bulk, or counted for monitoring purposes.
pub struct PluginRegistry {
    /// Internal map from plugin name to entry metadata.
    ///
    /// Protected by `RwLock` for concurrent read access with exclusive write.
    inner: RwLock<HashMap<String, PluginEntry>>,
}

impl PluginRegistry {
    /// Create a new empty registry (typically use [`GLOBAL_REGISTRY`] instead).
    pub fn new() -> Self {
        Self {
            inner: RwLock::new(HashMap::new()),
        }
    }

    /// Register a plugin into this registry.
    ///
    /// Called automatically by the `#[ctor]` function generated by
    /// `#[misogi_plugin]`. Manual registration is also supported for
    /// dynamic loading scenarios.
    ///
    /// # Arguments
    /// * `plugin` - Arc-wrapped plugin implementing [`PluginMetadata`].
    ///
    /// # Errors
    ///
    /// Returns [`MisogiError::Configuration`] if a plugin with the same name
    /// is already registered (duplicate detection).
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let my_plugin = Arc::new(MyCompliancePlugin);
    /// misogi_core::plugin_registry::GLOBAL_REGISTRY.register(my_plugin)?;
    /// ```
    pub fn register(&self, plugin: Arc<dyn PluginMetadata>) -> crate::error::Result<()> {
        let name = plugin.name().to_string();
        let version = plugin.version().to_string();
        let description = plugin.description().map(|s| s.to_string());
        let interfaces = plugin
            .implemented_interfaces()
            .into_iter()
            .map(|s| s.to_string())
            .collect();

        let mut map = self.inner.write();
        if map.contains_key(&name) {
            return Err(crate::error::MisogiError::Configuration(format!(
                "Plugin '{}' is already registered (version {})",
                name,
                map.get(&name).map(|e| e.version.as_str()).unwrap_or("?")
            )));
        }

        let entry = PluginEntry {
            name: name.clone(),
            version: version.clone(),
            description,
            interfaces,
        };

        map.insert(name.clone(), entry);

        tracing::debug!(
            plugin_name = %name,
            plugin_version = %version,
            total_plugins = map.len(),
            "Plugin registered into GLOBAL_REGISTRY"
        );

        Ok(())
    }

    /// List all currently registered plugins.
    ///
    /// Returns a snapshot of all plugin entries at the time of the call.
    /// The returned vector is ordered by registration order (insertion order).
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// for plugin in misogi_core::plugin_registry::GLOBAL_REGISTRY.list_plugins() {
    ///     println!("{} v{} — {}", plugin.name, plugin.version,
    ///              plugin.description.as_deref().unwrap_or("(no description)"));
    /// }
    /// ```
    pub fn list_plugins(&self) -> Vec<PluginEntry> {
        self.inner.read().values().cloned().collect()
    }

    /// Look up a specific plugin by its unique name.
    ///
    /// # Arguments
    /// * `name` - The exact plugin identifier (kebab-case).
    ///
    /// # Returns
    ///
    /// - `Some(PluginEntry)` if the plugin is registered.
    /// - `None` if no plugin with that name exists.
    pub fn get_plugin(&self, name: &str) -> Option<PluginEntry> {
        self.inner.read().get(name).cloned()
    }

    /// Return the total number of registered plugins.
    ///
    /// Useful for health checks and monitoring dashboards to verify
    /// that expected plugins have loaded successfully.
    pub fn plugin_count(&self) -> usize {
        self.inner.read().len()
    }

    /// Check whether a specific plugin name is registered.
    ///
    /// Faster than `get_plugin()` when only existence checking is needed
    /// (avoids cloning the full entry).
    pub fn has_plugin(&self, name: &str) -> bool {
        self.inner.read().contains_key(name)
    }

    /// Remove a plugin from the registry (for hot-reload / testing).
    ///
    /// # Arguments
    /// * `name` - The plugin identifier to remove.
    ///
    /// # Returns
    ///
    /// - `Some(PluginEntry)` if the plugin was removed.
    /// - `None` if the plugin was not found.
    #[allow(dead_code)]
    pub fn unregister(&self, name: &str) -> Option<PluginEntry> {
        let mut map = self.inner.write();
        map.remove(name)
    }
}

impl Default for PluginRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    struct MockPlugin;

    impl PluginMetadata for MockPlugin {
        fn name(&self) -> &'static str { "test_mock_plugin" }
        fn version(&self) -> &'static str { "0.1.0" }
        fn description(&self) -> Option<&'static str> { Some("A test mock plugin") }
        fn implemented_interfaces(&self) -> Vec<&'static str> {
            vec!["PluginMetadata", "CDRStrategy"]
        }
    }

    #[test]
    fn test_register_and_retrieve() {
        let registry = PluginRegistry::new();
        let plugin = Arc::new(MockPlugin);

        assert!(registry.register(plugin).is_ok());
        assert_eq!(registry.plugin_count(), 1);

        let entry = registry.get_plugin("test_mock_plugin");
        assert!(entry.is_some());
        let e = entry.unwrap();
        assert_eq!(e.name, "test_mock_plugin");
        assert_eq!(e.version, "0.1.0");
        assert_eq!(e.description.as_deref(), Some("A test mock plugin"));
        assert_eq!(e.interfaces.len(), 2);
    }

    #[test]
    fn test_duplicate_registration_fails() {
        let registry = PluginRegistry::new();
        let p1 = Arc::new(MockPlugin);
        let p2 = Arc::new(MockPlugin);

        assert!(registry.register(p1).is_ok());
        assert!(registry.register(p2).is_err());
        assert_eq!(registry.plugin_count(), 1);
    }

    #[test]
    fn test_list_plugins_returns_all() {
        let registry = PluginRegistry::new();
        assert!(registry.list_plugins().is_empty());

        let _ = registry.register(Arc::new(MockPlugin));
        assert_eq!(registry.list_plugins().len(), 1);
    }

    #[test]
    fn test_has_plugin() {
        let registry = PluginRegistry::new();
        assert!(!registry.has_plugin("nonexistent"));

        let _ = registry.register(Arc::new(MockPlugin));
        assert!(registry.has_plugin("test_mock_plugin"));
    }

    #[test]
    fn test_unregister_removes_plugin() {
        let registry = PluginRegistry::new();
        let _ = registry.register(Arc::new(MockPlugin));
        assert_eq!(registry.plugin_count(), 1);

        let removed = registry.unregister("test_mock_plugin");
        assert!(removed.is_some());
        assert_eq!(registry.plugin_count(), 0);
    }

    #[test]
    fn test_global_registry_exists() {
        // Global registry should be initialized and accessible
        // (plugin count may be 0 if no plugins are registered at test time)
        // Note: plugin_count() returns usize (unsigned), so >= 0 is always true
        let _count = GLOBAL_REGISTRY.plugin_count();
        assert!(_count <= usize::MAX);  // Trivially true, validates type system
    }
}
